version: "2"

services:
  nginx-proxy:
    image: nginx
    container_name: srv_nginx_proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - /srv/htdocs:/var/www:ro
      - ./certs:/etc/nginx/certs:ro
      - ./vhost.d/:/etc/nginx/vhost.d
      - ./conf.d/:/etc/nginx/conf.d
      - /usr/share/nginx/html
      - "media:/var/media:ro"
      - "static:/var/static:ro"
    networks:
      - proxy

  docker-gen:
    image: jwilder/docker-gen
    container_name: srv_docker_gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./templates:/etc/docker-gen/templates:ro
    expose:
      - 1024
    networks:
      - proxy
    volumes_from:
      - nginx-proxy
    entrypoint: /usr/local/bin/docker-gen -notify-sighup srv_nginx_proxy -watch -only-exposed -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-plugin:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: srv_letsencrypt_plugin
    volumes_from:
      - nginx-proxy
    networks:
      - proxy
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=srv_docker_gen

  registry:
    image: registry:2
    volumes:
      - ${PWD}/registry.yaml:/etc/docker/registry/config.yml
    ports:
      - "5000:5000"



networks:
  proxy:

volumes:
  media:
  static:
