version: "2"

services:

  wheel-factory:
    image: kmaginary/factory
    volumes:
      - /srv/build/wheelhouse:/wheelhouse
      - /srv/build/requirements.txt:/app/requirements.txt
    command: bash -c "while read p; do /env/bin/pip wheel $$p; done < requirements.txt"
  
  
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /srv/htdocs:/var/www:ro
      - /srv/certs:/etc/nginx/certs:ro
      - /srv/config/:/etc/nginx/vhost.d:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /usr/share/nginx/html
      - media:/var/media:ro
  
  letsencrypt-plugin:
    image: jrcs/letsencrypt-nginx-proxy-companion
    volumes_from:
      - nginx-proxy
    volumes:
      - /srv/config:/etc/nginx/vhost.d:rw
      - /srv/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  media:
